//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DunaHouseGombazo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conditioning
    {
        public Conditioning()
        {
            this.House = new HashSet<House>();
        }
    
        public int Id { get; set; }
        public string TextForm { get; set; }
    
        public virtual ICollection<House> House { get; set; }
    }
}
