//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DunaHouseGombazo
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Extras = new HashSet<Extra>();
        }
    
        public int Id { get; set; }
        public string SiteId { get; set; }
        public string LongName { get; set; }
        public string FullUrl { get; set; }
        public long Price { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public Nullable<int> RepresentativeId { get; set; }
    
        public virtual User CreatedByUser { get; set; }
        public virtual User LastEditedByUser { get; set; }
        public virtual ICollection<Extra> Extras { get; set; }
        public virtual User Representative { get; set; }
    }
}
